version: "3.8"

services:
  Web:
    image: hotshot824/wsp-server:1.0.0
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - ./web_server:/var/www/html
      - ./web_server/config/php.ini:/etc/php//8.1/cli/php.ini
    ports:
      - 80:80

  Database:
    image: mysql:8.0-debian
    restart: always
    environment:
      # MYSQL_ROOT_PASSWORD: test
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: WSP
    working_dir: /root/
    volumes:
      - ./db_server/data:/var/lib/mysql
      - ./db_server/init:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    depends_on:
      - Database
    environment:
      PMA_HOST: Database
      PMA_PORT: 3306
    ports:
      - "8080:80"